name: analysis

on:
  push:
    branches:
      - master

jobs:
  analysis:
    name: analysis

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: composer validate --strict
      run: composer validate

    - name: composer install
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: PHPCS
      run: composer phpcs

    - name: PHPStan
      run: composer phpstan
