name: codecov

on:
  push:
    branches:
      - dev
      - main

jobs:
  generate:
    name: generate

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1

    - name: composer validate --strict
      run: composer validate

    - name: composer install
      run: composer install

    - name: PHPUnit
      run: composer coverage -- --coverage-clover coverage.xml

    - name: save coverage.xml
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage.xml

  upload:
    name: upload

    runs-on: ubuntu-latest

    needs: [generate]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: download
        uses: actions/download-artifact@v3

      - name: upload
        uses: codecov/codecov-action@v3
